"""
pipeline/state.py
─────────────────
Shared TypedDict that defines the LangGraph agent state.
"""

from typing import TypedDict, List


class AgentState(TypedDict):
    idea: str
    user_name: str
    ideal_customer: str
    problem_solved: str
    search_results: str
    analysis: str
    is_new_chat: bool
    conversation_id: str
    messages: List[str]
    conversation_history: List[dict]
    optimized_query: str          # legacy single-query (kept for DB persistence)
    optimized_queries: List[str]  # multiple targeted queries generated by LLM
    current_message: str
