import os
import json
import logging
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Try to get the logger, if not, it will be standard
logger = logging.getLogger(__name__)

# Lazy initialization so the app doesn't crash if imported before pip install
embedder = None
qdrant_client = None
QDRANT_PATH = "./qdrant_data"
COLLECTION_NAME = "feasibility_context"

def _init_qdrant():
    global embedder, qdrant_client
    if qdrant_client is None:
        try:
            from qdrant_client import QdrantClient
            from qdrant_client.models import VectorParams, Distance
            from sentence_transformers import SentenceTransformer
            
            # This will download the model weights the first time it is run
            embedder = SentenceTransformer("all-MiniLM-L6-v2")
            qdrant_client = QdrantClient(path=QDRANT_PATH)
            
            if not qdrant_client.collection_exists(COLLECTION_NAME):
                qdrant_client.create_collection(
                    collection_name=COLLECTION_NAME,
                    vectors_config=VectorParams(size=384, distance=Distance.COSINE),
                )
        except ImportError as e:
            logger.error(f"Failed to initialize Qdrant/SentenceTransformers. Please install requirements: {e}")
            raise

def embed_conversation_context(conversation_id: str, search_results: str, analysis: str):
    """
    Chunks the search results and the final analysis, embeds them using MiniLM-L6-v2, 
    and inserts them into local Qdrant collection under the given conversation_id.
    """
    try:
        _init_qdrant()
    except ImportError:
        logger.warning("Skipping embedding because required dependencies are not installed.")
        return
        
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50,
        length_function=len
    )
    
    chunks = []
    
    # Chunk the search results
    if search_results:
        # Just simple splitting, source is web research
        sr_chunks = text_splitter.split_text(search_results)
        for chunk in sr_chunks:
            chunks.append({"text": chunk, "source": "web_research"})
            
    # Chunk the analysis (report)
    if analysis:
        try:
            clean_json = analysis.replace("```json", "").replace("```", "").strip()
            data = json.loads(clean_json)
            # Create a string representation to embed
            analysis_text = f"Feasibility Report generated by AI:\n"
            for k, v in data.items():
                if isinstance(v, list):
                    v = " ".join([str(item) for item in v])
                analysis_text += f"{k}: {v}\n"
        except Exception:
            analysis_text = analysis
            
        analysis_chunks = text_splitter.split_text(analysis_text)
        for chunk in analysis_chunks:
            chunks.append({"text": chunk, "source": "feasibility_report"})
            
    if not chunks:
        logger.info("Nothing to embed.")
        print("  [RAG] No text found to embed.")
        return
        
    texts = [c["text"] for c in chunks]
    metadatas = [{"conversation_id": conversation_id, "source": c["source"], "text": c["text"]} for c in chunks]
    
    print(f"\n  [RAG] 🧠 Generating embeddings for {len(chunks)} text chunks (Background Thread)...")

    # Generate vectors and upload to Qdrant
    try:
        from qdrant_client.models import PointStruct
        import uuid
        
        vectors = embedder.encode(texts)
        points = [
            PointStruct(
                id=str(uuid.uuid4()),
                vector=vector.tolist(),
                payload=meta
            )
            for vector, meta in zip(vectors, metadatas)
        ]
        
        qdrant_client.upsert(
            collection_name=COLLECTION_NAME,
            points=points
        )
        logger.info(f"Successfully embedded {len(points)} chunks for conversation {conversation_id}")
        print(f"  [RAG] ✅ Successfully uploaded {len(points)} chunks to Qdrant for Session {conversation_id[:8]}...\n")
    except Exception as e:
        logger.error(f"Error embedding context: {e}")
        print(f"  [RAG] ❌ Failed to embed context: {e}")
